on:
  push:
    branches-ignore:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Node 16.17 includes npm 8.15 which has a bug in npx
        node-version: [16.16.x, 18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
      - run: yarn
      - run: npx helloitsjoe/release-toolkit verify
      - run: yarn test
      - run: yarn lint
      - run: yarn coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
